# Generated by Django 4.2.6 on 2023-10-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_birth', models.DateField()),
                ('user_adress', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_tel', models.CharField(max_length=10)),
                ('user_login', models.CharField(max_length=50)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
                ('user_regist_date', models.DateField(auto_now=True)),
                ('user_login_date', models.DateTimeField(auto_now=True)),
                ('user_status', models.CharField(max_length=1)),
            ],
        ),
    ]
