# Generated by Django 4.2.6 on 2023-12-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_newtourregist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtourregist',
            name='TouristQuantity',
            field=models.SmallIntegerField(),
        ),
    ]
