# Generated by Django 4.2.6 on 2023-12-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_newtourregist_touristquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTourData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TourDestination', models.CharField(max_length=50)),
                ('DepartureFromOrigin', models.DateField()),
                ('ArrivalDestination', models.DateField()),
                ('TourHotel', models.CharField(max_length=50)),
                ('TouristQuantity', models.SmallIntegerField()),
                ('TourPrice', models.CharField(max_length=50)),
                ('TourType', models.CharField(max_length=50)),
                ('DepartureDestination', models.DateField()),
                ('ArrivalOrigin', models.DateField()),
                ('TourDeadline', models.DateField()),
                ('TourCreateDate', models.DateField()),
            ],
        ),
    ]
