# Generated by Django 4.2.6 on 2023-12-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_newtourdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewTourRegist',
        ),
    ]
