# Generated by Django 4.2.6 on 2023-12-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_delete_newtourregist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtourdata',
            name='ArrivalDestination',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='newtourdata',
            name='ArrivalOrigin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='newtourdata',
            name='DepartureFromOrigin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='newtourdata',
            name='TourCreateDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='newtourdata',
            name='TourDeadline',
            field=models.DateTimeField(),
        ),
    ]
