# Generated by Django 4.2.6 on 2023-12-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_newtourdata_arrivaldestination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtourdata',
            name='TourDeadline',
            field=models.CharField(max_length=50),
        ),
    ]
