# Generated by Django 4.2.6 on 2023-12-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_alter_newtourdata_tourdeadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtourdata',
            name='ArrivalOrigin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='newtourdata',
            name='TourDeadline',
            field=models.DateTimeField(blank=True),
        ),
    ]
