# Generated by Django 4.2.6 on 2023-12-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_newtourdata_arrivalorigin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtourdata',
            name='ArrivalDestination',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='newtourdata',
            name='ArrivalOrigin',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='newtourdata',
            name='DepartureDestination',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='newtourdata',
            name='DepartureFromOrigin',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='newtourdata',
            name='TourCreateDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
