# Generated by Django 4.2.6 on 2024-01-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_alter_newtourdata_arrivaldestination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TourID', models.CharField(max_length=50)),
                ('TouristName', models.CharField(max_length=50)),
                ('TouristBirth', models.DateField()),
                ('TouristAdress', models.CharField(max_length=50)),
                ('TouristEmail', models.EmailField(max_length=254)),
                ('TouristTel', models.CharField(max_length=10)),
                ('TouristIIN', models.CharField(max_length=50)),
                ('TouristPay', models.CharField(max_length=50)),
                ('TouristType', models.CharField(max_length=50)),
                ('RegistManager', models.CharField(max_length=50)),
                ('DateRegist', models.DateTimeField(auto_now=True)),
                ('ConfirmBuh', models.CharField(max_length=50)),
                ('StatusPay', models.CharField(max_length=1)),
                ('TouristLogin', models.CharField(max_length=50)),
                ('TouristPass', models.CharField(max_length=50)),
                ('TouristLastLogin', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
