# Generated by Django 4.2.6 on 2024-01-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_rename_touristlist_tourists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tourists',
            new_name='Clients',
        ),
    ]
