# Generated by Django 4.2.6 on 2024-01-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_rename_tourists_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='ConfirmBuh',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clients',
            name='RegistManager',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clients',
            name='StatusPay',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='TouristAdress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clients',
            name='TouristLogin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='TouristName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clients',
            name='TouristPass',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='TouristTel',
            field=models.CharField(max_length=12),
        ),
    ]
