# Generated by Django 4.2.6 on 2024-01-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_alter_clients_confirmbuh_alter_clients_registmanager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GidName', models.CharField(max_length=200)),
                ('GidBirth', models.DateField()),
                ('GidAdress', models.CharField(max_length=200)),
                ('GidEmail', models.EmailField(max_length=254)),
                ('GidTel', models.CharField(max_length=12)),
                ('GidCreateDate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlightType', models.CharField(max_length=50)),
                ('PaketName', models.CharField(max_length=50)),
                ('TourRoute', models.CharField(max_length=50)),
                ('DepartureFromOrigin', models.DateTimeField(blank=True)),
                ('TransitToArrival', models.DateTimeField(blank=True)),
                ('TransitToDeparture', models.DateTimeField(blank=True)),
                ('ArrivalDestination', models.DateTimeField(blank=True)),
                ('WaitingTimeTo', models.CharField(max_length=50)),
                ('DepartureFromDestination', models.DateTimeField(blank=True)),
                ('TransitFromArrival', models.DateTimeField(blank=True)),
                ('TransitFromDeparture', models.DateTimeField(blank=True)),
                ('ArrivalOrigin', models.DateTimeField(blank=True)),
                ('WaitingTimeFrom', models.CharField(max_length=50)),
                ('TouristQuantity', models.SmallIntegerField()),
                ('HotelMekka', models.CharField(max_length=50)),
                ('HotelJidda', models.CharField(max_length=50)),
                ('TourDeadline', models.DateTimeField(blank=True)),
                ('FlightTicket', models.DateTimeField(blank=True)),
                ('TouristVisa', models.DateTimeField(blank=True)),
                ('PriceMekkaHotel', models.DateTimeField(blank=True)),
                ('PriceMedinaHotel', models.DateTimeField(blank=True)),
                ('TourFood', models.DateTimeField(blank=True)),
                ('Transfer', models.DateTimeField(blank=True)),
                ('HadjKit', models.DateTimeField(blank=True)),
                ('Gid', models.DateTimeField(blank=True)),
                ('Comission', models.DateTimeField(blank=True)),
                ('TourDiscount', models.DateTimeField(blank=True)),
                ('TourSummary', models.DateTimeField(blank=True)),
                ('TourCreateDate', models.DateTimeField(blank=True)),
            ],
        ),
    ]
