# Generated by Django 4.2.6 on 2024-01-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_gids_tours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(max_length=50)),
                ('HotelCity', models.CharField(max_length=50)),
                ('StarsCity', models.CharField(max_length=50)),
                ('InfoHotel', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransportType', models.CharField(max_length=50)),
                ('TransportQuality', models.CharField(max_length=50)),
                ('TransferSeats', models.CharField(max_length=50)),
                ('TransportInfo', models.CharField(max_length=500)),
            ],
        ),
    ]
