# Generated by Django 4.2.6 on 2024-01-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_hotels_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='InfoHotel',
            new_name='HotelInfo',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='StarsCity',
            new_name='HotelStars',
        ),
    ]
