# Generated by Django 4.2.6 on 2024-01-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_rename_infohotel_hotels_hotelinfo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transfer',
            new_name='TourTransfer',
        ),
    ]
