# Generated by Django 4.2.6 on 2024-01-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_rename_transfer_tourtransfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tours',
        ),
    ]
