# Generated by Django 4.2.6 on 2024-01-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_tours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tours',
        ),
    ]
