# Generated by Django 4.2.6 on 2024-01-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_tours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewTourData',
        ),
    ]
