# Generated by Django 4.2.6 on 2024-01-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_delete_newtourdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
