# Generated by Django 4.2.6 on 2024-01-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
