# Generated by Django 4.2.6 on 2024-01-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
