# Generated by Django 4.2.6 on 2024-01-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0028_delete_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TouristName', models.CharField(max_length=200)),
                ('TouristBirth', models.DateField()),
                ('TouristAdress', models.CharField(max_length=200)),
                ('TouristIIN', models.CharField(max_length=50)),
                ('TouristPassNumber', models.CharField(max_length=50)),
                ('TouristPassEx', models.DateField()),
                ('TouristTel', models.CharField(max_length=12)),
                ('TouristRoomType', models.CharField(max_length=12)),
                ('TouristFoodType', models.CharField(max_length=12)),
                ('TouristPay', models.CharField(max_length=50)),
                ('TouristDebt', models.CharField(max_length=50)),
                ('TouristGroup', models.CharField(max_length=50)),
                ('RegistManager', models.CharField(max_length=200)),
                ('DateRegist', models.DateTimeField(auto_now=True)),
                ('ConfirmBuh', models.CharField(max_length=200)),
                ('StatusPay', models.CharField(max_length=50)),
                ('TouristLogin', models.CharField(max_length=100)),
                ('TouristPass', models.CharField(max_length=100)),
                ('TouristLastLogin', models.DateTimeField(auto_now=True)),
                ('TourID', models.CharField(max_length=50)),
            ],
        ),
    ]
