# Generated by Django 4.2.6 on 2024-02-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0030_delete_tours_alter_clients_touristfoodtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlightType', models.CharField(max_length=200)),
                ('PaketName', models.CharField(max_length=200)),
                ('TourRoute', models.CharField(max_length=200)),
                ('DepartureFromOrigin', models.DateTimeField(blank=True)),
                ('TransitToArrival', models.DateTimeField(blank=True)),
                ('TransitToDeparture', models.DateTimeField(blank=True)),
                ('ArrivalDestination', models.DateTimeField(blank=True)),
                ('WaitingTimeTo', models.CharField(max_length=50)),
                ('DepartureFromDestination', models.DateTimeField(blank=True)),
                ('TransitFromArrival', models.DateTimeField(blank=True)),
                ('TransitFromDeparture', models.DateTimeField(blank=True)),
                ('ArrivalOrigin', models.DateTimeField(blank=True)),
                ('WaitingTimeFrom', models.CharField(max_length=50)),
                ('TouristQuantity', models.SmallIntegerField()),
                ('HotelMekka', models.CharField(max_length=200)),
                ('HotelMedina', models.CharField(max_length=200)),
                ('FoodChoose', models.CharField(max_length=200)),
                ('GidChoose', models.CharField(max_length=200)),
                ('TransferChoose', models.CharField(max_length=200)),
                ('TourDeadline', models.DateTimeField(blank=True)),
                ('FlightTicketPrice', models.CharField(max_length=200)),
                ('TouristVisaPrice', models.CharField(max_length=200)),
                ('MekkaHotelPrice', models.CharField(max_length=200)),
                ('MedinaHotelPrice', models.CharField(max_length=200)),
                ('TourFoodPrice', models.CharField(max_length=200)),
                ('TransferPrice', models.CharField(max_length=200)),
                ('HadjKitPrice', models.CharField(max_length=200)),
                ('GidPrice', models.CharField(max_length=200)),
                ('Comission', models.CharField(max_length=200)),
                ('TourDiscount', models.CharField(max_length=200)),
                ('TourSummary', models.CharField(max_length=200)),
                ('TourCreateDate', models.DateTimeField(blank=True)),
            ],
        ),
    ]
