# Generated by Django 4.2.6 on 2024-03-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0033_tours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Tours',
        ),
    ]
