# Generated by Django 4.2.6 on 2024-03-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0035_clients_tours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tours',
        ),
    ]
