# Generated by Django 4.2.6 on 2024-03-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0038_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_status',
            field=models.CharField(default='off-line', max_length=10),
        ),
    ]
