# Generated by Django 4.2.6 on 2024-03-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0039_alter_users_user_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
