# Generated by Django 4.2.6 on 2024-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0041_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Block',
            field=models.CharField(default='---', max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='NoticeInfo',
            field=models.CharField(default='---', max_length=500),
        ),
    ]
