# Generated by Django 4.2.6 on 2024-03-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0042_alter_settings_block_alter_settings_noticeinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
