# Generated by Django 4.2.6 on 2024-04-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0044_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
