# Generated by Django 4.2.6 on 2024-04-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0046_clients_sitelogs_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='SiteLogs',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
