# Generated by Django 4.2.6 on 2024-04-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0048_clients_sitelogs_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteLogs',
        ),
    ]
