# Generated by Django 4.2.6 on 2024-04-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0052_alter_users_user_regist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AirlineName', models.CharField(max_length=200)),
                ('AirlineClass', models.CharField(max_length=200)),
                ('AirlineInfo', models.CharField(max_length=200)),
                ('AirlineAddDate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='test_db',
        ),
        migrations.RenameField(
            model_name='tours',
            old_name='TourFoodPrice',
            new_name='AirlineChoose',
        ),
        migrations.AddField(
            model_name='tours',
            name='FoodPriceAI',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='FoodPriceBB',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='FoodPriceFB',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='FoodPriceHB',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='FoodPriceRO',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='RoomChoose',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='RoomPriceDBL',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='RoomPriceQDR',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='RoomPriceSGL',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='RoomPriceTRP',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='user_login_date',
            field=models.DateTimeField(),
        ),
    ]
