# Generated by Django 4.2.6 on 2024-04-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0053_airlines_delete_test_db_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteLogs',
        ),
    ]
