# Generated by Django 4.2.6 on 2024-04-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0054_delete_sitelogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airlines',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.DeleteModel(
            name='Tours',
        ),
    ]
