# Generated by Django 4.2.6 on 2024-04-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0056_airlines_sitelogs_sitesettings_tours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='TransitFromArrival',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='TransitFromDeparture',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='TransitToArrival',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='TransitToDeparture',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='WaitingTimeFrom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tours',
            name='WaitingTimeTo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
