# Generated by Django 4.2.6 on 2024-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0057_alter_tours_transitfromarrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='TourCurrency',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='TourTime',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
