# Generated by Django 4.2.6 on 2024-04-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0058_tours_tourcurrency_tours_tourtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tours',
        ),
    ]
