# Generated by Django 4.2.6 on 2024-04-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0060_tours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteLogs',
            new_name='SiteEvents',
        ),
    ]
