# Generated by Django 4.2.6 on 2024-04-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0061_rename_sitelogs_siteevents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteEvents',
            new_name='SiteEventLogs',
        ),
    ]
