# Generated by Django 4.2.6 on 2024-04-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0062_rename_siteevents_siteeventlogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteEventLogs',
        ),
    ]
