# Generated by Django 4.2.6 on 2024-04-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0063_delete_siteeventlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEventLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventDateTime', models.DateTimeField(auto_now=True)),
                ('UserInfo', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=200)),
                ('LoginIP', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
            ],
        ),
    ]
